apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-service
  labels:
    app: selenium-chrome
spec:
  type: ClusterIP
  selector:
    app: selenium-chrome
  ports:
    - name: webdriver
      port: 4444
      targetPort: 4444
