apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml

patches:
  - path: patch-api.yaml
    target:
      kind: Deployment
      name: api

  - path: patch-selenium-antiaffinity.yaml
    target:
      kind: Deployment
      name: selenium-chrome

  - path: patch-selenium-nodeselector.yaml
    target:
      kind: Deployment
      name: selenium-chrome
